### ISSUE TITLE
Vendoring breaking pinterface interface

### ISSUE THREAD

**Issue by winterale** [xyproto/db#2]
It appears when you added in the vendor folder some paths in the imports were broken. When attempting to run userstate_test.go from the permissionsql package I get the following error:

 github.com/xyproto/permissionsql [github.com/xyproto/permissionsql.test]
<GOPATH>\src\github.com\xyproto\permissionsql\userstate.go:609: cannot use simplemaria.NewCreator(state.host) (type *simplemaria.MariaCreator) as type "github.com/xyproto/pinterface".ICreator in return argument:
	*simplemaria.MariaCreator does not implement "github.com/xyproto/pinterface".ICreator (wrong type for NewHashMap method)
		have NewHashMap(string) ("github.com/xyproto/simplemaria/vendor/github.com/xyproto/pinterface".IHashMap, error)
		want NewHashMap(string) ("github.com/xyproto/pinterface".IHashMap, error)
FAIL	github.com/xyproto/permissionsql [build failed]
Error: Tests failed.

**Comment by xyproto** [comment]
Thanks for reporting!

I'm unable to reproduce this problem.

When building locally, it works, and the CI tests works too: [build and test results at travis-ci.org](https://travis-ci.org/xyproto/simplemaria/builds/437228108)

Please try building with:

    env GO111MODULE=off go build

or:

    env GO111MODULE=on go build

And see if it makes any difference.

**Comment by winterale** [comment]
It must have been something on my end. I removed all of the xyproto libraries and re downloaded them with go get -u and it seems to have solved the problem. Thanks for the quick response.

**Comment by winterale** [comment]
It must have been something on my end. I removed all of the xyproto libraries and re downloaded them with go get -u and it seems to have solved the problem. Thanks for the quick response.
